# Generated by Django 3.2.6 on 2021-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField()),
                ('duracion', models.CharField(max_length=10)),
                ('album', models.CharField(max_length=150)),
                ('artista', models.CharField(max_length=150)),
                ('banda', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=150)),
                ('subgenero', models.CharField(max_length=150)),
                ('similares', models.CharField(max_length=255)),
                ('labels', models.CharField(max_length=255)),
                ('instrumentos', models.CharField(max_length=255)),
            ],
        ),
    ]
